import type { ProductContent } from "./product-model";

export const productCatalog = [
  {
    id: "product-moon-white-bowl",
    slug: "moon-white-bowl",
    titleKo: "달빛 백자 보울",
    shortDescription:
      "차분한 백색 유약과 손에 감기는 작은 굽을 가진 생활 보울입니다.",
    story:
      "매일의 식탁에서 가장 자주 손이 가는 크기를 기준으로 빚었습니다. 얇은 가장자리는 부드럽게 다듬고, 유약의 흐름은 담백하게 남겼습니다.",
    category: "cup",
    images: [
      {
        alt: "달빛 백자 보울 대표 이미지",
        isPrimary: true,
        placeholderLabel: "Moon Bowl",
      },
    ],
    kind: "regular",
    isLimited: false,
    limitedType: null,
    isArchived: false,
    restockCtaType: "restock_alert",
    commerce: {
      availabilityStatus: "available",
      currency: "KRW",
      price: 38000,
      source: "cafe24",
      stockQuantity: 4,
    },
    material: "백자토",
    glaze: "투명유",
    size: "지름 약 11cm, 높이 약 5cm",
    usageNote: "식기로 사용할 수 있습니다.",
    careNote: "강한 충격과 급격한 온도 변화를 피해 주세요.",
    shippingNote:
      "완충 포장 후 Cafe24 주문 정보를 기준으로 배송합니다.",
    published: true,
    publishedAt: "2026-05-05",
    createdAt: "2026-05-05T00:00:00.000Z",
    updatedAt: "2026-05-05T00:00:00.000Z",
  },
  {
    id: "product-ash-glaze-cup",
    slug: "ash-glaze-cup",
    titleKo: "재유 잔",
    shortDescription:
      "소성 흐름에 따라 유약의 표정이 달라지는 하나뿐인 잔입니다.",
    story:
      "같은 배합의 유약이어도 가마 안의 위치와 불의 흐름에 따라 색감이 조금씩 달라집니다. 이 잔은 가장자리의 옅은 흐름을 살려 아카이브합니다.",
    category: "cup",
    images: [
      {
        alt: "재유 잔 대표 이미지",
        isPrimary: true,
        placeholderLabel: "Ash Cup",
      },
    ],
    kind: "one_of_a_kind",
    isLimited: false,
    limitedType: null,
    isArchived: true,
    restockCtaType: "similar_work_alert",
    commerce: {
      availabilityStatus: "sold_out",
      currency: "KRW",
      price: 42000,
      source: "cafe24",
      stockQuantity: 0,
    },
    material: "분청토",
    glaze: "재유",
    size: "지름 약 8cm, 높이 약 7cm",
    usageNote: "차와 작은 음료를 담기 좋습니다.",
    careNote: "사용 후 충분히 건조해 보관해 주세요.",
    shippingNote: "예전 판매 완료 아카이브 작업물입니다.",
    published: true,
    publishedAt: "2026-05-05",
    createdAt: "2026-05-05T00:00:00.000Z",
    updatedAt: "2026-05-05T00:00:00.000Z",
  },
  {
    id: "product-kiln-limited-vase",
    slug: "kiln-limited-vase",
    titleKo: "계절 소성 한정 화병",
    shortDescription:
      "이번 계절 소성에서만 제작하는 작은 화병입니다.",
    story:
      "계절별 유약 테스트와 소성 분위기를 기록하기 위한 한정 작업입니다. 같은 가마 안에서만 만들어지는 색과 질감을 중심으로 소개합니다.",
    category: "limited",
    images: [
      {
        alt: "계절 소성 한정 화병 대표 이미지",
        isPrimary: true,
        placeholderLabel: "Limited Vase",
      },
    ],
    kind: "one_of_a_kind",
    isLimited: true,
    limitedType: "kiln_batch",
    isArchived: false,
    restockCtaType: "next_limited_alert",
    commerce: {
      availabilityStatus: "upcoming",
      currency: "KRW",
      price: 68000,
      source: "cafe24",
      stockQuantity: 1,
    },
    material: "혼합토",
    glaze: "계절 테스트 유약",
    size: "높이 약 13cm",
    usageNote: "드라이플라워와 작은 생화를 꽂기 좋습니다.",
    careNote: "물 사용 후 바닥면을 충분히 말려 주세요.",
    shippingNote: "입고 일정 확정 후 Cafe24 상품으로 연결합니다.",
    published: true,
    publishedAt: "2026-05-05",
    createdAt: "2026-05-05T00:00:00.000Z",
    updatedAt: "2026-05-05T00:00:00.000Z",
  },
] as const satisfies ProductContent[];
